(function(k){function q(d){d=d.split("&");for(var h={},i=0;i<d.length;i++){var f=d[i].split("=");if("undefined"!=typeof f[0]){var j=f[0];h[j]=decodeURIComponent("undefined"!=typeof f[1]?f[1]:j)}}return h}function b(d,h,i,f){var j="window";$.each(d.split("."),function(){j+="."+this;"undefined"==eval("typeof "+j)&&eval(j+"={};")});eval(d+"_="+d);this.proxy=function(){var p=this,l=arguments,m=arguments.callee;if(i)k[d.replace(/\..*$/,"")]=undefined;else eval(d+"="+d+"_");k[d+"_"]=undefined;return h(function(){try{var n=
eval(d)}catch(s){return false}if("function"!=typeof n)return false;if(n==arguments.callee)return false;for(key in m)if(n[key])for(_key in m[key])n[key][_key]=m[key][_key];else n[key]=m[key];return n.apply(p,l)},f)};eval(d+"=this['proxy']")}if(k.ACMS)return false;var c=document.getElementById("acms-js"),g={};if(c){c=c.src.split("?");if(1<c.length){c=q(c[1]);for(key in c)g[key]=c[key]}}g.searchEngineKeyword="";if(document.referrer.match(/^http:\/\/www\.google\..*(?:\?|&)q=([^&]+).*$|^http:\/\/search\.yahoo\.co\.jp.*(?:\?|&)p=([^&]+).*$|^http:\/\/www\.bing\.com.*(?:\?|&)q=([^&]+).*$/))g.searchEngineKeyword=
decodeURIComponent(RegExp.$1||RegExp.$2||RegExp.$3).replace(/\+/g," ");g.root="/";if(g.offset)g.root+=g.offset+"/";g.jsRoot=g.root+g.jsDir;g.hash=k.document.location.hash;g.Gmap={sensor:k.navigator.userAgent.match(/iPhone|Android/)?"true":"false"};c=g.jsRoot;var o=k.navigator.userAgent.match(/MSIE/)?new ActiveXObject("Msxml2.XMLHTTP"):new XMLHttpRequest;o.open("get",c+"library/jquery/jquery-"+g.jQuery+".min.js",false);o.send(null);eval(o.responseText);var r=function(){};r.parseQuery=q;var a=function(d,
h,i,f){d="string"==typeof d?d:"";h="string"==typeof h?h:"";i=$.isFunction(i)?i:function(){};f=$.isFunction(f)?f:function(){};return function(j,p){$.isFunction(j)||(j=function(){});var l=arguments.callee;if(l.executed)if(l.loaded)return j();else{l.stack.push(j);return true}else{l.executed=true;l.stack=[j];if(p){i();$.ajax({url:d,dataType:"script",scriptCharset:h,complete:function(){f();for(l.loaded=true;l.stack.length;)l.stack.shift()()}});return true}else{o.open("get",d,false);o.send(null);var m=
o.responseText;i();with(k)eval(m);f();l.loaded=true;return j()}}}};a.css=function(d,h,i){if(!d)return false;var f=document.createElement("link");f.type="text/css";f.rel="stylesheet";if(h)f.charset=h;f.href=d;d=document.getElementsByTagName("head")[0];i&&d.firstChild?d.insertBefore(f,d.firstChild):d.appendChild(f);return true};a.Dispatch=a(c+"dispatch.js");a.Dispatch._static2dynamic=a(c+"dispatch/_static2dynamic.js");a.Dispatch._validate=a(c+"dispatch/_validate.js");a.Dispatch.highslide=a(c+"dispatch/highslide.js");
a.Dispatch.ckeditor=a(c+"dispatch/ckeditor.js");a.Dispatch.emoditor=a(c+"dispatch/emoditor.js");a.Dispatch.Utility=a(c+"dispatch/utility.js");a.Dispatch.Postinclude=a(c+"dispatch/postinclude.js");a.Dispatch.Postinclude._postinclude=a(c+"dispatch/postinclude/_postinclude.js");a.Dispatch.Linkmatchlocation=a(c+"dispatch/linkmatchlocation.js");a.Dispatch.Admin=a(c+"dispatch/admin.js");a.Dispatch.Admin._tooltip=a(c+"dispatch/admin/_tooltip.js");a.Dispatch.Admin.Configunit=a(c+"dispatch/admin/configunit.js");
a.Dispatch.Edit=a(c+"dispatch/edit.js");a.Dispatch.Edit._add=a(c+"dispatch/edit/_add.js");a.Dispatch.Edit._change=a(c+"dispatch/edit/_change.js");a.Dispatch.Edit._emojiedit=a(c+"dispatch/edit/_emojiedit.js");a.Dispatch.Edit._item=a(c+"dispatch/edit/_item.js");a.Dispatch.Edit._tagassist=a(c+"dispatch/edit/_tagassist.js");a.Dispatch.Edit._category=a(c+"dispatch/edit/_category.js");a.Dispatch.Edit._inplace=a(c+"dispatch/edit/_inplace.js");a.Dispatch.Edit.map=a(c+"dispatch/edit/map.js");a.Library=a(c+
"library.js");a.Library.validator=a(c+"library/validator.js");a.Library.highslide=a(c+"library/highslide/highslide.js",null,function(){k.hs=undefined},function(){e.Dispatch._highslideInit()});a.Library.swfobject=a(c+"library/swfobject/swfobject.js",null,function(){k.hs=undefined});a.Library.ckeditor=a(c+"library/ckeditor/ckeditor.js",null,function(){k.CKEDITOR=undefined;e.Dispatch._ckeditorPre()},function(){e.Dispatch._ckeditorPost()});a.Library.Jquery={};a.Library.Jquery.biggerlink=a(c+"library/jquery/jquery.biggerlink.min.js");
a.Library.Jquery.cookie=a(c+"library/jquery/jquery.cookie.js");a.Library.Jquery.selection=a(c+"library/jquery/jquery.selection.js");a.Library.Jquery.prettyphoto=a(c+"library/jquery/prettyphoto/jquery.prettyPhoto.js",null,function(){a.css(e.Config.jsRoot+"library/jquery/prettyphoto/css/prettyPhoto.css")});a.Library.Jquery.Ui={};a.Library.Jquery.Ui.core=a(c+"library/jquery/ui/jquery.ui.core.min.js",null,function(){a.css(e.Config.jsRoot+"library/jquery/ui/css/"+e.Config.uiTheme+"/jquery.ui.theme.css");
a.css(e.Config.jsRoot+"library/jquery/ui/css/"+e.Config.uiTheme+"/jquery.ui.core.css")});a.Library.Jquery.Ui.widget=a(c+"library/jquery/ui/jquery.ui.widget.min.js",null,function(){e.Load.Library.Jquery.Ui.core()});a.Library.Jquery.Ui.mouse=a(c+"library/jquery/ui/jquery.ui.mouse.min.js");a.Library.Jquery.Ui.position=a(c+"library/jquery/ui/jquery.ui.position.min.js");a.Library.Jquery.Ui.draggable=a(c+"library/jquery/ui/jquery.ui.draggable.min.js",null,function(){e.Load.Library.Jquery.Ui.mouse()});a.Library.Jquery.Ui.resizable=
a(c+"library/jquery/ui/jquery.ui.resizable.min.js",null,function(){a.css(e.Config.jsRoot+"library/jquery/ui/css/"+e.Config.uiTheme+"/jquery.ui.resizable.css");e.Load.Library.Jquery.Ui.mouse()});a.Library.Jquery.Ui.sortable=a(c+"library/jquery/ui/jquery.ui.sortable.min.js",null,function(){e.Load.Library.Jquery.Ui.mouse()});a.Library.Jquery.Ui.accordion=a(c+"library/jquery/ui/jquery.ui.accordion.min.js",null,function(){a.css(e.Config.jsRoot+"library/jquery/ui/css/"+e.Config.uiTheme+"/jquery.ui.accordion.css")});
a.Library.Jquery.Ui.button=a(c+"library/jquery/ui/jquery.ui.button.min.js",null,function(){a.css(e.Config.jsRoot+"library/jquery/ui/css/"+e.Config.uiTheme+"/jquery.ui.button.css")});a.Library.Jquery.Ui.dialog=a(c+"library/jquery/ui/jquery.ui.dialog.min.js",null,function(){a.css(e.Config.jsRoot+"library/jquery/ui/css/"+e.Config.uiTheme+"/jquery.ui.dialog.css");e.Load.Library.Jquery.Ui.draggable();e.Load.Library.Jquery.Ui.resizable();e.Load.Library.Jquery.Ui.button()});a.Library.Jquery.Ui.tabs=a(c+
"library/jquery/ui/jquery.ui.tabs.min.js",null,function(){a.css(e.Config.jsRoot+"library/jquery/ui/css/"+e.Config.uiTheme+"/jquery.ui.tabs.css")});a.Library.Jquery.Ui.datepicker=a(c+"library/jquery/ui/jquery.ui.datepicker.min.js",null,function(){a.css(e.Config.jsRoot+"library/jquery/ui/css/"+e.Config.uiTheme+"/jquery.ui.datepicker.css");e.Load.Library.Jquery.Ui.core()});a.Library.google=a(k.location.protocol+"//www.google.com/jsapi?key="+g.googleApiKey);var e=function(){};e.Config=function(d,h){if(!d)return"";
if("string"==typeof d)if(h){this.Config[d]=h;return true}else return"undefined"!=typeof this.Config[d]?this.Config[d]:"";else $.extend(arguments.callee,d)};e.Load=a;e.Dispatch=function(){};e.Library=r;k.ACMS=e;b("ACMS.Dispatch",a.Dispatch);b("ACMS.Dispatch._tagassist",a.Dispatch._tagassist);b("ACMS.Dispatch._static2dynamic",a.Dispatch._static2dynamic);b("ACMS.Dispatch._validate",a.Dispatch._validate);b("ACMS.Dispatch._highslideInit",a.Dispatch.highslide);b("ACMS.Dispatch._ckeditorPre",a.Dispatch.ckeditor);
b("ACMS.Dispatch._ckeditorPost",a.Dispatch.ckeditor);b("ACMS.Dispatch.highslide",a.Dispatch.highslide);b("ACMS.Dispatch.ckeditor",a.Dispatch.ckeditor);b("ACMS.Dispatch.emoditor",a.Dispatch.emoditor);b("ACMS.Dispatch.Utility",a.Dispatch.Utility);b("ACMS.Dispatch.Postinclude.ready",a.Dispatch.Postinclude);b("ACMS.Dispatch.Postinclude.submit",a.Dispatch.Postinclude);b("ACMS.Dispatch.Postinclude._postinclude",a.Dispatch.Postinclude._postinclude);b("ACMS.Dispatch.Linkmatchlocation.part",a.Dispatch.Linkmatchlocation);
b("ACMS.Dispatch.Linkmatchlocation.full",a.Dispatch.Linkmatchlocation);b("ACMS.Dispatch.Linkmatchlocation.blog",a.Dispatch.Linkmatchlocation);b("ACMS.Dispatch.Linkmatchlocation.category",a.Dispatch.Linkmatchlocation);b("ACMS.Dispatch.Linkmatchlocation.entry",a.Dispatch.Linkmatchlocation);b("ACMS.Dispatch.Admin",a.Dispatch.Admin);b("ACMS.Dispatch.Admin._tooltip",a.Dispatch.Admin._tooltip);b("ACMS.Dispatch.Admin.Configunit",a.Dispatch.Admin.Configunit);b("ACMS.Dispatch.Admin.Configunit._add",a.Dispatch.Admin.Configunit);
b("ACMS.Dispatch.Admin.Configunit.remove",a.Dispatch.Admin.Configunit);b("ACMS.Dispatch.Edit",a.Dispatch.Edit);b("ACMS.Dispatch.Edit._add",a.Dispatch.Edit._add);b("ACMS.Dispatch.Edit._change",a.Dispatch.Edit._change);b("ACMS.Dispatch.Edit._emojiedit",a.Dispatch.Edit._emojiedit);b("ACMS.Dispatch.Edit._item",a.Dispatch.Edit._item);b("ACMS.Dispatch.Edit._tagassist",a.Dispatch.Edit._tagassist);b("ACMS.Dispatch.Edit._category",a.Dispatch.Edit._category);b("ACMS.Dispatch.Edit._inplace",a.Dispatch.Edit._inplace);
b("ACMS.Dispatch.Edit.updatetime",a.Dispatch.Edit);b("ACMS.Dispatch.Edit.map",a.Dispatch.Edit.map);b("ACMS.Library.scrollTo",a.Library);b("ACMS.Library.scrollToElm",a.Library);b("ACMS.Library.dl2object",a.Library);b("ACMS.Library.switchStyle",a.Library);b("ACMS.Library.getPostData",a.Library);b("ACMS.Library.acmsLink",a.Library);b("ACMS.Library.Validator.isFunction",a.Library.validator);b("hs.expand",a.Library.highslide,true);b("swfobject.embedSWF",a.Library.swfobject,true);b("CKEDITOR.replace",a.Library.ckeditor,
true);b("jQuery.widget",a.Library.Jquery.Ui.widget);b("jQuery.fn.position",a.Library.Jquery.Ui.position);b("jQuery.fn.draggable",a.Library.Jquery.Ui.draggable);b("jQuery.fn.sortable",a.Library.Jquery.Ui.sortable);b("jQuery.fn.accordion",a.Library.Jquery.Ui.accordion);b("jQuery.fn.tabs",a.Library.Jquery.Ui.tabs);b("jQuery.fn.dialog",a.Library.Jquery.Ui.dialog);b("jQuery.fn.datepicker",a.Library.Jquery.Ui.datepicker);b("jQuery.cookie",a.Library.Jquery.cookie);b("jQuery.fn.biggerlink",a.Library.Jquery.biggerlink);
b("jQuery.fn.selection",a.Library.Jquery.selection);b("jQuery.fn.prettyPhoto",a.Library.Jquery.prettyphoto);b("google.load",a.Library.google,false,true);$.extend(e.Config,g);a(c+"config.js")()})(window);$(function(){ACMS.Dispatch(document)});
